# Generated by Django 4.0 on 2023-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="image name")),
                ("image", models.ImageField(upload_to="", verbose_name="image")),
            ],
        ),
    ]
