# Generated by Django 3.1.4 on 2020-12-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_auto_20200917_1056"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["title", "author"]},
        ),
    ]
